apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carbonledger
  namespace: carbonledger
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - carbonledger.com
    - www.carbonledger.com
    - api.carbonledger.com
    secretName: carbonledger-tls
  rules:
  - host: carbonledger.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: www.carbonledger.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: api.carbonledger.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
