/**
 * CarbonLedger — Marketplace Load Tests (#687)
 *
 * Three scenarios:
 *
 *   marketplace_browse     — updated to current pagination API; 500 VUs / 5 min
 *   purchase_stress        — 50 VUs completing full purchase flows / 5 min
 *   bulk_retirement_spike  — 10 VUs × 10-item bulk retirements (year-end ESG rush)
 *
 * Thresholds:
 *   p99 < 2000ms, error_rate < 1% for all scenarios
 *
 * Pre-requisites:
 *   1. Run scripts/seed-loadtest.sh to populate 1000 active listings.
 *   2. Obtain a JWT: POST /api/v1/auth/login → set JWT env var.
 *   3. Set BASE_URL to your staging server.
 *
 * Run:
 *   k6 run load-tests/marketplace.k6.js
 *
 * With env overrides:
 *   k6 run -e BASE_URL=https://staging.carbonledger.io \
 *           -e JWT=eyJ... \
 *           load-tests/marketplace.k6.js
 *
 * With JSON results for RESULTS.md baseline:
 *   k6 run --out json=load-tests/results/run-$(date +%Y%m%d).json \
 *           load-tests/marketplace.k6.js
 *
 * Flamegraph profiling:
 *   Start the Node.js backend with:
 *     node --prof dist/main.js
 *   Run the load test, then convert:
 *     node --prof-process isolate-*.log > profile.txt
 *   See load-tests/RESULTS.md §Profiling for details.
 */

import http from "k6/http";
import { check, sleep, group } from "k6";
import { Rate, Trend, Counter } from "k6/metrics";
import { uuidv4 } from "https://jslib.k6.io/k6-utils/1.4.0/index.js";

// ── Configuration ─────────────────────────────────────────────────────────────

const BASE_URL = __ENV.BASE_URL || "http://localhost:3001";
const API      = `${BASE_URL}/api/v1`;
const JWT      = __ENV.JWT || "";

// Seed data: must be created by scripts/seed-loadtest.sh before running.
// The seed script writes listing IDs to load-tests/seed-data.json.
// If not present, fall back to well-known test IDs.
let LISTING_IDS = [];
try {
  const seedData = JSON.parse(open("./seed-data.json"));
  LISTING_IDS = seedData.listingIds || [];
} catch (_) {
  // Fallback: generated by seed-loadtest.sh convention
  LISTING_IDS = Array.from({ length: 20 }, (_, i) =>
    `listing-loadtest-${String(i + 1).padStart(4, "0")}`
  );
}

// ── Custom metrics ────────────────────────────────────────────────────────────

const browseErrors          = new Rate("browse_errors");
const purchaseErrors        = new Rate("purchase_errors");
const retirementErrors      = new Rate("retirement_errors");

const browseDuration        = new Trend("browse_duration",      true);
const purchaseDuration      = new Trend("purchase_duration",    true);
const retirementDuration    = new Trend("retirement_duration",  true);

const purchaseCount         = new Counter("purchase_total");
const retirementCount       = new Counter("retirement_total");

// ── Test options ──────────────────────────────────────────────────────────────

export const options = {
  scenarios: {
    // ── Scenario 1: Marketplace Browse ────────────────────────────────────────
    // Updated to match current API pagination (page/pageSize query params).
    marketplace_browse: {
      executor:          "ramping-vus",
      startVUs:          0,
      stages: [
        { duration: "30s", target: 500 },
        { duration: "5m",  target: 500 },
        { duration: "30s", target: 0   },
      ],
      gracefulRampDown:  "15s",
      tags:              { scenario: "browse" },
    },

    // ── Scenario 2: Purchase Stress ────────────────────────────────────────────
    // 50 VUs each completing a full purchase flow (auth → browse → purchase)
    // over 5 minutes.
    purchase_stress: {
      executor:          "ramping-vus",
      startVUs:          0,
      stages: [
        { duration: "30s", target: 50  },
        { duration: "5m",  target: 50  },
        { duration: "30s", target: 0   },
      ],
      gracefulRampDown:  "15s",
      tags:              { scenario: "purchase" },
      // Start purchase scenario 30s after browse starts (realistic ramp order)
      startTime:         "30s",
    },

    // ── Scenario 3: Bulk Retirement Spike ────────────────────────────────────
    // 10 VUs each submitting 10-item bulk retirements.
    // Simulates year-end ESG reporting rush where all large buyers retire at once.
    bulk_retirement_spike: {
      executor:          "per-vu-iterations",
      vus:               10,
      iterations:        5,    // each VU submits 5 bulk retirements × 10 items
      maxDuration:       "10m",
      tags:              { scenario: "bulk_retirement" },
      startTime:         "1m",
    },
  },

  thresholds: {
    // All scenarios: p99 < 2000ms
    "browse_duration":     ["p(99)<2000"],
    "purchase_duration":   ["p(99)<2000"],
    "retirement_duration": ["p(99)<2000"],

    // Overall error rates < 1%
    "browse_errors":     ["rate<0.01"],
    "purchase_errors":   ["rate<0.01"],
    "retirement_errors": ["rate<0.01"],

    // HTTP-level failures < 1%
    "http_req_failed": ["rate<0.01"],
  },
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function randomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function authHeaders() {
  const headers = { "Content-Type": "application/json" };
  if (JWT) headers["Authorization"] = `Bearer ${JWT}`;
  return headers;
}

/** Generate a wallet-style public key for test buyers. */
function buyerKey(vu) {
  return `GBLOADTEST${String(vu).padStart(46, "0").slice(0, 46)}`;
}

// ── Setup: verify reachability and warm up ────────────────────────────────────

export function setup() {
  const health = http.get(`${BASE_URL}/health`);
  if (health.status !== 200) {
    throw new Error(
      `API health check failed: status=${health.status} url=${BASE_URL}/health\n` +
      `Ensure the staging server is running and run scripts/seed-loadtest.sh first.`
    );
  }
  console.log(`✓ API reachable at ${BASE_URL}`);
  console.log(`✓ ${LISTING_IDS.length} listing IDs loaded`);

  if (!JWT) {
    console.warn(
      "⚠  No JWT set — purchase and retirement requests will receive 401. " +
      "Set -e JWT=<token> for full scenario coverage."
    );
  }

  return { listingIds: LISTING_IDS };
}

// ── Scenario 1: Marketplace Browse ────────────────────────────────────────────
// Tests the paginated GET /marketplace/listings endpoint.
// Updated to use ?page=N&pageSize=20 (current API contract).

function scenarioBrowse() {
  const methodologies = ["VCS", "Gold Standard", "ACR", "CAR", "Plan Vivo"];
  const vintages      = ["2020", "2021", "2022", "2023", "2024"];
  const page          = Math.ceil(Math.random() * 5); // pages 1–5

  group("marketplace_browse", () => {
    // ── GET /marketplace/listings (paginated) ─────────────────────────────────
    const params = new URLSearchParams({
      page:        String(page),
      pageSize:    "20",
      methodology: randomItem(methodologies),
      vintage:     randomItem(vintages),
    });

    const res = http.get(`${API}/marketplace/listings?${params}`, {
      tags: { name: "GET /listings" },
    });

    browseDuration.add(res.timings.duration);

    const ok = check(res, {
      "browse: status 200":        (r) => r.status === 200,
      "browse: has data array":    (r) => {
        try {
          const body = r.json();
          return Array.isArray(body.data || body) || typeof body === "object";
        } catch { return false; }
      },
      "browse: response < 2000ms": (r) => r.timings.duration < 2000,
    });

    browseErrors.add(!ok || res.status >= 500);

    // 40% of browsers also fetch a single listing detail
    if (Math.random() < 0.4 && LISTING_IDS.length > 0) {
      const listingId = randomItem(LISTING_IDS);
      const detail = http.get(`${API}/marketplace/listings/${listingId}`, {
        tags: { name: "GET /listing/:id" },
      });
      check(detail, {
        "listing detail: 200 or 404": (r) => r.status === 200 || r.status === 404,
      });
    }
  });

  sleep(0.5 + Math.random());
}

// ── Scenario 2: Purchase Stress ────────────────────────────────────────────────
// Each VU completes a full flow: browse listing → post purchase → check receipt.

function scenarioPurchase() {
  const listingId = randomItem(LISTING_IDS);

  group("purchase_flow", () => {
    // Step 1: browse a listing to confirm availability
    const browse = http.get(`${API}/marketplace/listings/${listingId}`, {
      tags: { name: "GET /listing (pre-purchase)" },
    });

    // 404 means seed data is exhausted — treat as non-error
    if (browse.status === 404) {
      return;
    }

    check(browse, { "pre-purchase browse: 200": (r) => r.status === 200 });

    // Step 2: post the purchase
    const payload = JSON.stringify({
      listingId,
      amount:         1,
      buyerPublicKey: buyerKey(__VU),
    });

    const purchase = http.post(`${API}/marketplace/purchase`, payload, {
      headers: authHeaders(),
      tags:    { name: "POST /purchase" },
    });

    purchaseDuration.add(purchase.timings.duration);

    const ok = check(purchase, {
      "purchase: 201 created or 400 conflict": (r) =>
        r.status === 201 || r.status === 400 || r.status === 401,
      "purchase: response < 2000ms": (r) => r.timings.duration < 2000,
    });

    // Only count 5xx as purchase errors
    purchaseErrors.add(purchase.status >= 500);

    if (ok && purchase.status === 201) {
      purchaseCount.add(1);

      // Step 3: verify receipt (optional — non-blocking)
      try {
        const txHash = purchase.json("txHash");
        if (txHash) {
          http.get(`${API}/marketplace/receipt/${txHash}`, {
            tags: { name: "GET /receipt" },
          });
        }
      } catch (_) { /* JSON parse errors are non-fatal here */ }
    }
  });

  sleep(1 + Math.random() * 2);
}

// ── Scenario 3: Bulk Retirement Spike ─────────────────────────────────────────
// Simulates 10 large corporate buyers all submitting 10-item bulk retirements
// simultaneously — the year-end ESG reporting rush.

function scenarioBulkRetirement() {
  group("bulk_retirement", () => {
    // Build a 10-item retirement batch
    const items = Array.from({ length: 10 }, (_, i) => ({
      batchId:     randomItem(LISTING_IDS),
      amount:      1,
      beneficiary: `Corp-VU${__VU}-Item${i}`,
      reason:      `Year-end ESG offset ${new Date().getFullYear()} — item ${i + 1}/10`,
    }));

    const payload = JSON.stringify({
      retirements: items,
      corporateName: `LoadTestCorp-VU${__VU}`,
      reportingPeriod: `${new Date().getFullYear()}-FY`,
    });

    const res = http.post(`${API}/retirements/bulk`, payload, {
      headers: authHeaders(),
      tags:    { name: "POST /retirements/bulk" },
    });

    retirementDuration.add(res.timings.duration);

    const ok = check(res, {
      "bulk retire: 201 or 400 or 401":  (r) =>
        r.status === 201 || r.status === 400 || r.status === 401,
      "bulk retire: response < 2000ms":  (r) => r.timings.duration < 2000,
    });

    // 5xx = error; 400/401 without JWT = expected in load env
    retirementErrors.add(res.status >= 500);

    if (res.status === 201) {
      retirementCount.add(1);
    }
  });

  sleep(2 + Math.random() * 3);
}

// ── Main entry point ─────────────────────────────────────────────────────────
// Route each VU to its scenario based on exec.scenario.name.

import exec from "k6/execution";

export default function (data) {
  const scenario = exec.scenario.name;

  if (scenario === "marketplace_browse") {
    scenarioBrowse();
  } else if (scenario === "purchase_stress") {
    scenarioPurchase();
  } else if (scenario === "bulk_retirement_spike") {
    scenarioBulkRetirement();
  } else {
    // Fallback: run browse
    scenarioBrowse();
  }
}

// ── Teardown: print summary ───────────────────────────────────────────────────

export function teardown(data) {
  console.log("=== Load Test Complete ===");
  console.log(`Listing IDs used: ${data.listingIds.length}`);
  console.log("Check load-tests/RESULTS.md for baseline comparison.");
}
